<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Product[]
     */
    public function findActive()
    {
       return $this->createQueryBuilder('product')
        -> where('product.id = 1')
        ->getQuery()
        ->getResult();
    }
    public function findActive2()
    {
        return $this->createQueryBuilder('product')
            -> where('product.active = true')
            ->getQuery()
            ->getResult();
    }

    public function findActive3()//подготовленные запрос -актив какое именно значение
    {
        return $this->createQueryBuilder('product')
            ->join('product.category', 'category')
            -> where('product.active = :active')
            ->andWhere('category.active= :active')
            ->setParameter('active', false)
            ->getQuery()
            ->getResult();
    }

    public function findByCategory(Category $category)//передаём сюда целую категорию
    {
        return $this
            ->createQueryBuilder('product')
            -> where('product.active = :active')
            -> andWhere('product.category = :category')//это плейсхлдер на который нужно посетить какой-то параметр
            ->setParameter('active', 1)
            ->setParameter('category', $category)//посетили просто категорию, объект более абстрактно на доктрин языке
            ->getQuery()
            ->getResult();
    }


}
